### ISSUE TITLE
Random quote generator

### ISSUE THREAD

**Issue by jondeaves** [jondeaves/tcm-bot#5]
It was a feature of the Forum. Let's make it a feature of the Bot.

Quotes Sources: 
* http://www.creationasylum.net/index.php?act=quotes&CODE=01.
* http://www.creationasylum.net/index.php?showtopic=12715&hl=quotes

Given the amount of quotes (35 pages) it's probably work writing a script to crawl the page and extract them then save to our own Database?

**Comment by chenasraf** [comment]
Closed by #27.
